# Generated by Django 4.1.1 on 2022-09-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WLANCodesWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
