# Generated by Django 4.1.1 on 2022-09-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WLANCodesWebApp', '0005_alter_student_code_alter_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
