# Generated by Django 4.1.1 on 2022-09-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WLANCodesWebApp', '0007_alter_student_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=11)),
            ],
        ),
        migrations.DeleteModel(
            name='ListDeletion',
        ),
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='code',
            name='type',
            field=models.CharField(choices=[('h', 'Stunde(n)'), ('d', 'Tag(e)'), ('y', 'Jahr')], max_length=10),
        ),
    ]
