# Generated by Django 4.1.1 on 2022-09-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WLANCodesWebApp', '0008_codedeletion_delete_listdeletion_alter_code_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codedeletion',
            name='firstname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codedeletion',
            name='group',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codedeletion',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
