# Generated by Django 4.1.1 on 2022-09-15 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WLANCodesWebApp', '0009_codedeletion_firstname_codedeletion_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codedeletion',
            old_name='code',
            new_name='code_to_delete',
        ),
    ]
