# Generated by Django 4.1.1 on 2022-09-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WLANCodesWebApp', '0010_rename_code_codedeletion_code_to_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
