# Generated by Django 4.1.1 on 2022-09-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WLANCodesWebApp', '0011_alter_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('noreply-mail', 'noreply-E-Mail zum Versand der Schadenmeldung')], max_length=50)),
                ('setting', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
