# Generated by Django 4.1.1 on 2022-09-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WLANCodesWebApp', '0012_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='type',
            field=models.CharField(choices=[('m', 'Minuten'), ('h', 'Stunde(n)'), ('d', 'Tag(e)'), ('y', 'Jahr')], max_length=10),
        ),
    ]
