# Generated by Django 4.1.1 on 2022-09-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WLANCodesWebApp', '0013_alter_code_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(choices=[('noreply-mail', 'noreply-E-Mail zum Versand der Schadenmeldung'), ('lnk_controller', 'Link zum WLAN-Controller')], max_length=50),
        ),
    ]
