# Generated by Django 4.1.1 on 2022-09-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WLANCodesWebApp', '0014_alter_config_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='setting',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
