# Generated by Django 4.1.1 on 2022-10-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WLANCodesWebApp', '0015_alter_config_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(choices=[('noreply-mail', 'noreply-E-Mail-Absenderadresse zum Versand der Codes'), ('mail_text', 'Mailtext zum Versand der Codes'), ('lnk_controller', 'Link zum WLAN-Controller')], max_length=50),
        ),
    ]
