# Generated by Django 4.1.5 on 2023-07-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WLANCodesWebApp', '0016_config_text_alter_config_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.TextField()),
                ('school', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(choices=[('noreply-mail', 'noreply-E-Mail-Absenderadresse'), ('mail_text', 'Mailtext zum Versand der Codes'), ('lnk_controller', 'Link zum WLAN-Controller'), ('access', 'Access Key'), ('accounts_mail_text', 'Mailtext bei Accounterstellung')], max_length=50),
        ),
    ]
