# Generated by Django 4.0.5 on 2022-06-19 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fach', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Fächer',
            },
        ),
        migrations.CreateModel(
            name='Kompetenzkarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorie', models.CharField(max_length=50)),
                ('jgst', models.CharField(choices=[('05', 'Jgst. 5'), ('06', 'Jgst. 6'), ('07', 'Jgst. 7'), ('08', 'Jgst. 8'), ('09', 'Jgst. 9'), ('10', 'Jgst. 10'), ('11', 'Jgst. EF'), ('12', 'Jgst. Q1'), ('13', 'Jgst. Q2')], max_length=2)),
                ('vorhaben', models.CharField(max_length=200)),
                ('info', models.CharField(max_length=200)),
                ('medien', models.CharField(max_length=200)),
                ('fach', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mkr.fach')),
            ],
            options={
                'verbose_name_plural': 'Kompetenzkarten',
            },
        ),
    ]
