# Generated by Django 4.0.5 on 2022-06-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkr', '0003_kompetenzkarte_alle_teil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kompetenzkarte',
            name='kategorie',
            field=models.CharField(choices=[('11', 'Medienausstattung'), ('12', 'Digitale Werkzeuge')], max_length=2),
        ),
    ]
