# Generated by Django 4.0.5 on 2022-07-03 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mkr', '0005_kompetenzkarte_file_alter_kompetenzkarte_kategorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kompetenzkarte',
            old_name='file',
            new_name='download',
        ),
    ]
