# Generated by Django 4.0.5 on 2022-07-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkr', '0007_alter_kompetenzkarte_alle_teil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kompetenzkarte',
            name='alle_teil',
            field=models.CharField(blank=True, choices=[('0', 'ist für alle '), ('1', 'Teilgruppe')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='kompetenzkarte',
            name='durchf_planung',
            field=models.CharField(blank=True, choices=[('0', 'wird durchgeführt'), ('1', 'Planung/Umsetzung')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='kompetenzkarte',
            name='pflicht_empf',
            field=models.CharField(blank=True, choices=[('0', 'Pflicht'), ('1', 'Empfehlung')], max_length=1, null=True),
        ),
    ]
