# Generated by Django 4.2.2 on 2023-06-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkr', '0008_alter_kompetenzkarte_alle_teil_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fach',
            options={'ordering': ['fach'], 'verbose_name_plural': 'Fächer'},
        ),
        migrations.AlterField(
            model_name='kompetenzkarte',
            name='alle_teil',
            field=models.CharField(choices=[('0', 'für alle '), ('1', 'eine Teilgruppe')], max_length=1),
        ),
        migrations.AlterField(
            model_name='kompetenzkarte',
            name='durchf_planung',
            field=models.CharField(choices=[('0', 'wird durchgeführt'), ('1', 'Planung/Umsetzung')], max_length=1),
        ),
        migrations.AlterField(
            model_name='kompetenzkarte',
            name='pflicht_empf',
            field=models.CharField(choices=[('0', 'Pflicht'), ('1', 'Empfehlung')], max_length=1),
        ),
    ]
