# Generated by Django 4.1.5 on 2023-06-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkr', '0009_alter_fach_options_alter_kompetenzkarte_alle_teil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kompetenzkarte',
            name='medienkenntnisse_lul',
            field=models.CharField(default='-', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kompetenzkarte',
            name='vorwissen_sus',
            field=models.CharField(default='-', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kompetenzkarte',
            name='alle_teil',
            field=models.CharField(choices=[('0', 'ist für alle '), ('1', 'ist für eine Teilgruppe')], max_length=1),
        ),
        migrations.AlterField(
            model_name='kompetenzkarte',
            name='durchf_planung',
            field=models.CharField(choices=[('0', 'wird durchgeführt'), ('1', 'wird geplant/erprobt')], max_length=1),
        ),
        migrations.AlterField(
            model_name='kompetenzkarte',
            name='info',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='kompetenzkarte',
            name='medienkompetenz',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='kompetenzkarte',
            name='pflicht_empf',
            field=models.CharField(choices=[('0', 'ist Pflicht'), ('1', 'ist Empfehlung')], max_length=1),
        ),
        migrations.AlterField(
            model_name='kompetenzkarte',
            name='technik',
            field=models.CharField(max_length=400),
        ),
    ]
