# Generated by Django 4.1.5 on 2024-04-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkr', '0011_kompetenzkarte_changed_kompetenzkarte_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kompetenzkarte',
            options={'ordering': ['kategorie', 'fach', 'jgst'], 'verbose_name_plural': 'Kompetenzkarten'},
        ),
        migrations.AlterField(
            model_name='kompetenzkarte',
            name='jgst',
            field=models.CharField(choices=[('05', 'Jgst. 5'), ('06', 'Jgst. 6'), ('07', 'Jgst. 7'), ('08', 'Jgst. 8'), ('09', 'Jgst. 9'), ('10', 'Jgst. 10'), ('11', 'Jgst. EF'), ('12', 'Jgst. Q1'), ('13', 'Jgst. Q2'), ('JG', 'mehrere Jgst.')], max_length=2),
        ),
    ]
