# Generated by Django 4.1.5 on 2023-02-09 17:13

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('buchungstool_settings', '0001_initial'), ('buchungstool_settings', '0002_alter_config_name_alter_config_setting'), ('buchungstool_settings', '0003_config_text'), ('buchungstool_settings', '0004_alter_config_setting'), ('buchungstool_settings', '0005_alter_config_setting'), ('buchungstool_settings', '0006_alter_config_text')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('E-Mail', 'Ziel-E-Mail für Schadenmeldungen'), ('noreply-mail', 'noreply-E-Mail zum Versand der Schadenmeldung'), ('info-frontpage', 'info-frontpage')], max_length=50)),
                ('setting', models.CharField(blank=True, max_length=30)),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
            ],
        ),
    ]
