# Generated by Django 4.1.5 on 2023-02-12 09:25

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool_settings', '0001_squashed_0006_alter_config_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=50)),
                ('email_to', models.CharField(blank=True, max_length=50)),
                ('noreply_mail', models.CharField(blank=True, max_length=50)),
                ('info_frontpage', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
            ],
        ),
    ]
