# Generated by Django 4.1.5 on 2023-02-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool_settings', '0008_setting_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='access_token',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='setting',
            name='email_host',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='setting',
            name='email_host_password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='setting',
            name='email_host_user',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='setting',
            name='email_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='setting',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
    ]
