# Generated by Django 4.1.5 on 2023-02-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool_settings', '0009_setting_access_token_setting_email_host_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='school',
            new_name='institution',
        ),
    ]
