# Generated by Django 4.1.5 on 2023-03-01 21:15

from django.db import migrations, models
# import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool_settings', '0011_setting_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='email_host_password_enc',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
