# Generated by Django 4.1.5 on 2023-03-12 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool_settings', '0012_setting_email_host_password_enc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='email_host_password',
        ),
    ]
