# Generated by Django 4.1.5 on 2023-04-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool_settings', '0013_remove_setting_email_host_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='student_access_token',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
