# Generated by Django 4.1.5 on 2023-04-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool_settings', '0014_setting_student_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='access_token',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='setting',
            name='student_access_token',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
