# Generated by Django 4.1.5 on 2023-04-11 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool_settings', '0015_alter_setting_access_token_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
    ]
