# Generated by Django 4.2.11 on 2024-03-22 14:30

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool_settings', '0016_delete_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='info_frontpage',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
