# Generated by Django 4.2.11 on 2024-03-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool_settings', '0017_alter_setting_info_frontpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='email_host_password_enc',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
