# Generated by Django 4.2.11 on 2024-03-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool_settings', '0018_alter_setting_email_host_password_enc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='email_host',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='email_host_password_enc',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='email_host_user',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='email_port',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='email_use_tls',
        ),
    ]
