# Generated by Django 5.0.3 on 2024-03-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool_settings', '0019_remove_setting_email_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='dsb_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
