# Generated by Django 5.0.3 on 2024-03-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool_settings', '0020_setting_dsb_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='dsb_link',
            field=models.URLField(blank=True),
        ),
    ]
