# Generated by Django 5.0.3 on 2024-03-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool_settings', '0021_alter_setting_dsb_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='mkr_link',
            field=models.URLField(blank=True),
        ),
    ]
