# Generated by Django 5.0.3 on 2024-04-02 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool_settings', '0022_setting_mkr_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='access_token',
        ),
    ]
