# Generated by Django 4.0.2 on 2022-04-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10)),
                ('lerngruppe', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('datum', models.DateField()),
                ('stunde', models.IntegerField()),
            ],
        ),
    ]
