# Generated by Django 4.0.2 on 2022-05-01 08:43

from datetime import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0003_userlist_krzl'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='created',
            field=models.DateTimeField(default=datetime.now),
        ),
    ]
