# Generated by Django 4.0.2 on 2022-05-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0004_userlist_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
