"""
Django settings for edutools_site project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# load .env file if it exists
load_dotenv(BASE_DIR / ".env")


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in ("1", "true", "yes", "on")


def env_int(name, default=0):
    value = os.environ.get(name)

    if value is None or value == "":
        return default

    return int(value)


def env_list(name, default=""):
    value = os.environ.get(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-dev-only-change-me"
)

DEBUG = env_bool("DEBUG", default=False)

ALLOWED_HOSTS = env_list(
    "ALLOWED_HOSTS",
    default="localhost,127.0.0.1"
)

CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS", default="")

# Falls nginx oder später ein HTTPS-Reverse-Proxy davor sitzt
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Email settings
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", default=True)

EMAIL_HOST = os.environ.get("EMAIL_HOST", "")

EMAIL_PORT = env_int("EMAIL_PORT", default=587)

EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")

EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")

DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    EMAIL_HOST_USER
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'edutools_home',
    'WLANCodesWebApp',
    'codeimport',
    'accounts',
    'buchungstool',
    'userlist',
    'devicelist',
    'buchungstool_settings',
    'mkr',
    'qrcode_generator',
    'library_manager',
    'appointment',
    'activity',
    'dsb',
    'upload',
    'django_ckeditor_5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # add rate limit middleware to get custom error page for rate limit errors
    'django_ratelimit.middleware.RatelimitMiddleware',
]

RATELIMIT_VIEW = "accounts.views.rate_limit_exceeded_view"

ROOT_URLCONF = 'edutools_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                # add media for logo via context processor
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # make instution name and logo available to base.html via context processors
                'buchungstool.context_processors.add_institution',
                # get logout url for base.html via context processor
                'buchungstool.context_processors.get_logout_url',
                # get login hint for login.html
                'edutools_home.context_processors.get_login_hint',
                # get legal notice link for edutools_base
                'edutools_home.context_processors.get_legal_notice',
                # get privacy policy link for edutools_base
                'edutools_home.context_processors.get_privacy_policy',
            ],
        },
    },
]

WSGI_APPLICATION = 'edutools_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# allow overriding the sqlite path from environment (e.g. Docker)
SQLITE_PATH = os.environ.get("SQLITE_PATH")
if SQLITE_PATH is None or SQLITE_PATH == "":
    SQLITE_PATH = str(BASE_DIR / "db.sqlite3")
else:
    SQLITE_PATH = str(SQLITE_PATH)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': SQLITE_PATH,
    }
}

DATA_UPLOAD_MAX_NUMBER_FIELDS = 2000

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'de-de'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.environ.get('STATIC_ROOT', os.path.join(BASE_DIR, 'public/static'))

# media root should be kept private on the webserver, so files are served through
# Django with a view which can be access restricted
MEDIA_ROOT = os.environ.get('MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading',
            '|',
            'bold',
            'italic',
            'link',
            'bulletedList',
            'numberedList',
            'blockQuote',
            # 'imageUpload',
            ],
    },
    'extends': {
        'toolbar': [
            'heading',
            '|',
            'outdent',
            'indent',
            '|',
            'bold',
            'italic',
            'link',
            'underline',
            'strikethrough',
            'code',
            'subscript',
            'superscript',
            'highlight',
            '|',
            'codeBlock',
            'sourceEditing',
            # 'insertImage',
            'bulletedList',
            'numberedList',
            # 'todoList',
            '|',
            'blockQuote',
            # 'imageUpload',
            '|',
            'fontSize',
            'fontFamily',
            'fontColor',
            'fontBackgroundColor',
            # 'mediaEmbed',
            'removeFormat',
            'insertTable',
            ],
        'table': {
            'contentToolbar': [
                'tableColumn',
                'tableRow',
                'mergeTableCells',
                'tableProperties',
                'tableCellProperties'
                ],
        },
        'wordCount': {
            'displayWords': False,
            'displayCharacters': False
        }
    }
}
