# Generated by Django 5.0.8 on 2024-09-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['time']},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='booked',
        ),
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='parents_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='student_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
