# Generated by Django 5.0.8 on 2024-09-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_options_remove_appointment_booked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='email_2',
            field=models.EmailField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
