# Generated by Django 5.0.8 on 2024-09-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointment_email_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='primary_school',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
