# Generated by Django 5.0.8 on 2024-09-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointment_primary_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email_2',
            field=models.EmailField(blank=True, max_length=200),
        ),
    ]
