# Generated by Django 5.0.8 on 2024-10-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_alter_appointment_email_alter_appointment_email_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
