# Generated by Django 5.0.8 on 2024-11-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0006_appointmentmail"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="phone",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
