# Generated by Django 4.2.16 on 2025-01-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_appointment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmail',
            name='mail_text_reminder',
            field=models.TextField(blank=True, null=True),
        ),
    ]
