# Generated by Django 5.2.4 on 2025-11-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_appointmentmail_mail_text_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
