# Generated by Django 5.2.4 on 2025-11-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_appointment_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('show_empty_days', models.BooleanField(default=True)),
            ],
        ),
    ]
