# Generated by Django 4.0.2 on 2022-05-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=10)),
                ('datum', models.DateField()),
                ('stunde', models.IntegerField()),
                ('beschreibung', models.CharField(max_length=300)),
                ('krzl', models.CharField(max_length=10)),
                ('behoben', models.CharField(max_length=10)),
            ],
        ),
    ]
