# Generated by Django 4.0.2 on 2022-05-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicelist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.CharField(default='', max_length=10),
        ),
    ]
