# Generated by Django 4.0.2 on 2022-05-28 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0013_booking_pen_01_booking_pen_02_booking_pen_03_and_more'),
        ('devicelist', '0002_device_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='room',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='buchungstool.room'),
        ),
    ]
