# Generated by Django 4.0.2 on 2022-05-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicelist', '0003_alter_device_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='behoben',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
