# Generated by Django 4.0.2 on 2022-05-30 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0013_booking_pen_01_booking_pen_02_booking_pen_03_and_more'),
        ('devicelist', '0004_alter_device_behoben'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Device',
            new_name='DevicelistEntry',
        ),
    ]
