# Generated by Django 4.0.2 on 2022-06-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicelist', '0006_alter_devicelistentry_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=10)),
                ('dbname', models.CharField(max_length=10)),
            ],
        ),
    ]
