# Generated by Django 4.0.2 on 2022-06-05 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devicelist', '0007_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelistentry',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='devicelist.device'),
        ),
    ]
