# Generated by Django 4.0.2 on 2022-06-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicelist', '0008_alter_devicelistentry_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
