# Generated by Django 4.0.2 on 2022-06-11 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devicelist', '0009_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelistentry',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='devicelist.status'),
        ),
    ]
