# Generated by Django 4.0.2 on 2022-06-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicelist', '0010_devicelistentry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='color',
            field=models.CharField(default='text-danger', max_length=20),
            preserve_default=False,
        ),
    ]
