# Generated by Django 4.0.2 on 2022-06-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devicelist', '0011_status_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicelistentry',
            options={'verbose_name_plural': 'DevicelistEntries'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status'},
        ),
    ]
