# Generated by Django 4.0.2 on 2022-09-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicelist', '0012_alter_devicelistentry_options_alter_status_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('E-Mail', 'E-Mail für Schadenmeldungen'), ('Schule', 'Name der Schule für Kopfzeile')], max_length=50)),
                ('setting', models.CharField(max_length=100)),
            ],
        ),
    ]
