# Generated by Django 4.0.2 on 2022-09-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicelist', '0013_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(choices=[('E-Mail', 'Ziel-E-Mail für Schadenmeldungen'), ('noreply-mail', 'noreply-E-Mail zum Versand der Schadenmeldung')], max_length=50),
        ),
    ]
