# Generated by Django 4.0.2 on 2022-09-04 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devicelist', '0014_alter_setting_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
