# Generated by Django 4.1.5 on 2023-03-28 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devicelist', '0016_device_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='type',
        ),
    ]
