# Generated by Django 4.1.5 on 2023-03-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicelist', '0017_remove_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device',
            field=models.CharField(max_length=30),
        ),
    ]
