# Generated by Django 4.1.5 on 2023-04-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devicelist', '0018_alter_device_device'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['device']},
        ),
    ]
