# Generated by Django 4.1.5 on 2023-04-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicelist', '0020_alter_devicelistentry_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='dbname',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
