# Generated by Django 4.1.5 on 2023-04-15 07:19

import devicelist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicelist', '0021_device_position_alter_device_dbname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='position',
            field=models.PositiveIntegerField(default=devicelist.models.Device.get_next_number),
        ),
    ]
