# Generated by Django 4.1.5 on 2023-06-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devicelist', '0022_alter_device_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['position']},
        ),
    ]
