# Generated by Django 4.1.5 on 2023-07-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_user_profile_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='RegistrationID',
        ),
    ]
