# Generated by Django 4.1.5 on 2023-02-09 17:03

import django_ckeditor_5.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('buchungstool', '0001_initial'), ('buchungstool', '0002_rename_buchungen_buchung'), ('buchungstool', '0003_auto_20220218_2250'), ('buchungstool', '0004_buchung_krzl'), ('buchungstool', '0005_rename_buchung_booking'), ('buchungstool', '0006_room'), ('buchungstool', '0007_room_short_name_alter_room_id'), ('buchungstool', '0008_booking_room'), ('buchungstool', '0009_alter_booking_lerngruppe_alter_room_description_and_more'), ('buchungstool', '0010_room_card'), ('buchungstool', '0011_booking_ipad_01_booking_ipad_02_booking_ipad_03_and_more'), ('buchungstool', '0012_room_alert'), ('buchungstool', '0013_booking_pen_01_booking_pen_02_booking_pen_03_and_more'), ('buchungstool', '0014_device'), ('buchungstool', '0015_delete_device'), ('buchungstool', '0016_room_type'), ('buchungstool', '0017_alter_room_type'), ('buchungstool', '0018_alter_room_alert'), ('buchungstool', '0019_booking_series_id')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('short_name', models.CharField(default='short name', max_length=10)),
                ('card', models.IntegerField(default=1)),
                ('alert', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('type', models.CharField(blank=True, choices=[('iPad', 'iPad-Koffer'), ('CR', 'Computerraum'), ('other', 'anderer Raum')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lerngruppe', models.CharField(max_length=30)),
                ('datum', models.DateField(default=django.utils.timezone.now)),
                ('stunde', models.IntegerField(default=0)),
                ('krzl', models.CharField(default='', max_length=3)),
                ('room', models.CharField(default='', max_length=10)),
                ('iPad_01', models.CharField(blank=True, max_length=40)),
                ('iPad_02', models.CharField(blank=True, max_length=40)),
                ('iPad_03', models.CharField(blank=True, max_length=40)),
                ('iPad_04', models.CharField(blank=True, max_length=40)),
                ('iPad_05', models.CharField(blank=True, max_length=40)),
                ('iPad_06', models.CharField(blank=True, max_length=40)),
                ('iPad_07', models.CharField(blank=True, max_length=40)),
                ('iPad_08', models.CharField(blank=True, max_length=40)),
                ('iPad_09', models.CharField(blank=True, max_length=40)),
                ('iPad_10', models.CharField(blank=True, max_length=40)),
                ('iPad_11', models.CharField(blank=True, max_length=40)),
                ('iPad_12', models.CharField(blank=True, max_length=40)),
                ('iPad_13', models.CharField(blank=True, max_length=40)),
                ('iPad_14', models.CharField(blank=True, max_length=40)),
                ('iPad_15', models.CharField(blank=True, max_length=40)),
                ('iPad_16', models.CharField(blank=True, max_length=40)),
                ('pen_01', models.CharField(blank=True, max_length=2)),
                ('pen_02', models.CharField(blank=True, max_length=2)),
                ('pen_03', models.CharField(blank=True, max_length=2)),
                ('pen_04', models.CharField(blank=True, max_length=2)),
                ('pen_05', models.CharField(blank=True, max_length=2)),
                ('pen_06', models.CharField(blank=True, max_length=2)),
                ('pen_07', models.CharField(blank=True, max_length=2)),
                ('pen_08', models.CharField(blank=True, max_length=2)),
                ('pen_09', models.CharField(blank=True, max_length=2)),
                ('pen_10', models.CharField(blank=True, max_length=2)),
                ('pen_11', models.CharField(blank=True, max_length=2)),
                ('pen_12', models.CharField(blank=True, max_length=2)),
                ('pen_13', models.CharField(blank=True, max_length=2)),
                ('pen_14', models.CharField(blank=True, max_length=2)),
                ('pen_15', models.CharField(blank=True, max_length=2)),
                ('pen_16', models.CharField(blank=True, max_length=2)),
                ('series_id', models.CharField(blank=True, max_length=32)),
            ],
        ),
    ]
