# Generated by Django 3.2.3 on 2022-02-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buchungen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lerngruppe', models.CharField(max_length=20)),
            ],
        ),
    ]
