# Generated by Django 4.1.5 on 2023-02-17 14:21

import buchungstool.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0021_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='position',
            field=models.PositiveSmallIntegerField(default=buchungstool.models.Category.get_next_number),
        ),
    ]
