# Generated by Django 4.1.5 on 2023-02-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0022_alter_category_options_alter_category_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#ebebeb', max_length=7),
        ),
    ]
