# Generated by Django 4.1.5 on 2023-02-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0024_room_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['category']},
        ),
        migrations.AddField(
            model_name='room',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
