# Generated by Django 4.1.5 on 2023-02-18 21:42

import buchungstool.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0025_alter_room_options_room_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='position',
            field=models.PositiveIntegerField(default=buchungstool.models.Room.get_next_number),
        ),
    ]
