# Generated by Django 4.1.5 on 2023-02-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0026_alter_room_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['category', 'position']},
        ),
        migrations.AlterField(
            model_name='room',
            name='card',
            field=models.IntegerField(default=0),
        ),
    ]
