# Generated by Django 4.1.5 on 2023-03-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0027_alter_room_options_alter_room_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_first_of_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='is_last_of_category',
            field=models.BooleanField(default=False),
        ),
    ]
