# Generated by Django 4.1.5 on 2023-06-02 14:38

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0028_room_is_first_of_category_room_is_last_of_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', django_ckeditor_5.fields.CKEditor5Field()),
                ('answer', django_ckeditor_5.fields.CKEditor5Field()),
            ],
        ),
    ]
