# Generated by Django 4.1.5 on 2023-08-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0032_alter_room_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='type',
            new_name='device_count',
        ),
    ]
