# Generated by Django 4.1.5 on 2023-08-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0033_rename_type_room_device_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='iPad_17',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='iPad_18',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='iPad_19',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='iPad_20',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='iPad_21',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='iPad_22',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='iPad_23',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='iPad_24',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='iPad_25',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='iPad_26',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='iPad_27',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='iPad_28',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='iPad_29',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='iPad_30',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_17',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_18',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_19',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_20',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_21',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_22',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_23',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_24',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_25',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_26',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_27',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_28',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_29',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_30',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
