# Generated by Django 4.2.11 on 2024-03-22 14:30

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0035_alter_booking_ipad_01_alter_booking_ipad_02_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='room',
            name='alert',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
