# Generated by Django 5.0.8 on 2024-10-03 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activityblock_remove_activity_student_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='bookedactivity',
            options={'verbose_name_plural': 'Booked Activities'},
        ),
    ]
