# Generated by Django 5.0.10 on 2025-07-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_bookedactivity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.AddField(
            model_name='activity',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of this activity'),
        ),
        migrations.AddField(
            model_name='activityblock',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of this block'),
        ),
    ]
