# Generated by Django 5.2.4 on 2025-11-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_activity_options_activity_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
    ]
