# Generated by Django 5.2.4 on 2025-11-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_activitysettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivitySettings',
            new_name='ActivitySetting',
        ),
    ]
