# Generated by Django 4.0.6 on 2023-10-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadone',
            name='file',
            field=models.FileField(upload_to='upload'),
        ),
    ]
