# Generated by Django 4.0.6 on 2023-10-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_uploadone_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadone',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='upload'),
        ),
    ]
