# Generated by Django 4.2.6 on 2023-10-28 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_alter_uploadone_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadOne',
            new_name='Upload',
        ),
    ]
