# Generated by Django 4.2.6 on 2023-10-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_rename_uploadone_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadLaufband',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=500)),
            ],
        ),
    ]
