# Generated by Django 4.2.6 on 2023-10-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_uploadlaufband'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadlaufband',
            old_name='text',
            new_name='text_mz',
        ),
        migrations.AddField(
            model_name='uploadlaufband',
            name='text_nz',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
