# Generated by Django 4.2.6 on 2023-10-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_rename_text_uploadlaufband_text_mz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadlaufband',
            name='text_mz',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='uploadlaufband',
            name='text_nz',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
