# Generated by Django 5.1.6 on 2025-11-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_alter_uploadlaufband_text_mz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
            ],
        ),
    ]
