# Generated by Django 5.2.4 on 2025-11-22 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Order for display (lower numbers appear first)')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cards_pages', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_cards_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cards Page',
                'verbose_name_plural': 'Cards Pages',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#009641', help_text='Hex color code (e.g., #009641)', max_length=7)),
                ('order', models.IntegerField(default=0, help_text='Order within the page (lower numbers appear first)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('cards_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='eduCards.cardspage')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['cards_page', 'order', 'name'],
                'unique_together': {('cards_page', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Main content of the card')),
                ('additional_info', models.TextField(blank=True, help_text='Additional information', null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='eduCards/attachments/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0, help_text='Order within the category (lower numbers appear first)')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cards', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_cards', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='eduCards.category')),
            ],
            options={
                'ordering': ['category', 'order', 'title'],
            },
        ),
    ]
