# Generated by Django 5.2.12 on 2026-05-01 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduCards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CardsPageAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cards_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='eduCards.cardspage')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cards_page_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cards Page Access Token',
                'verbose_name_plural': 'Cards Page Access Tokens',
                'ordering': ['cards_page', '-created'],
            },
        ),
    ]
