# Generated by Django 5.2.12 on 2026-05-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduCards', '0002_alter_card_created_by_cardspageaccesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardspageaccesstoken',
            name='access_level',
            field=models.CharField(choices=[('view', 'View Only'), ('edit', 'View & Create Cards')], default='edit', max_length=10),
        ),
    ]
