# Generated by Django 5.2.12 on 2026-05-01 21:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduCards', '0003_cardspageaccesstoken_access_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cardspage',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Teachers who can access this page besides the creator.', related_name='shared_cards_pages', to=settings.AUTH_USER_MODEL),
        ),
    ]
