# Generated by Django 5.2.15 on 2026-07-26 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduCards', '0004_cardspage_shared_with'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='eduCards/attachments/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='eduCards.card')),
            ],
            options={
                'ordering': ['created', 'id'],
            },
        ),
    ]
