# Generated by Django 5.0.3 on 2024-04-02 20:03

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdutoolsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10)),
                ('login_hint', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
            ],
        ),
    ]
