# Generated by Django 5.0.3 on 2024-04-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edutools_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdutoolsSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10)),
                ('login_hint', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EdutoolsSettings',
        ),
    ]
