# Generated by Django 5.0.8 on 2024-10-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edutools_home', '0002_edutoolssetting_delete_edutoolssettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='edutoolssetting',
            name='legal_notice',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='edutoolssetting',
            name='privacy_policy',
            field=models.URLField(blank=True),
        ),
    ]
