# Generated by Django 5.2.9 on 2026-05-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DsbName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsb1', models.CharField(max_length=100)),
                ('dsb2', models.CharField(max_length=100)),
            ],
        ),
    ]
