# Generated by Django 5.2.9 on 2026-05-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsb', '0002_dsbname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsbname',
            name='dsb1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dsbname',
            name='dsb2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
