# Generated by Django 5.0.3 on 2024-04-29 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_manager', '0002_alter_inventoryitem_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library_manager.librarycategory', to_field='name'),
        ),
        migrations.AlterField(
            model_name='librarycategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
