# Generated by Django 5.0.3 on 2024-04-29 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_manager', '0003_alter_inventoryitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='library_manager.librarylocation', to_field='name'),
        ),
        migrations.AlterField(
            model_name='librarylocation',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
