# Generated by Django 4.2.11 on 2024-04-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_manager', '0004_alter_inventoryitem_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(max_length=120),
        ),
    ]
