# Generated by Django 4.2.11 on 2024-04-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_manager', '0005_alter_inventoryitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='author',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='created',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='existing',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='last_edit',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
