# Generated by Django 4.2.11 on 2024-04-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_manager', '0007_alter_inventoryitem_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='existing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventory_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='last_edit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
