# Generated by Django 4.2.11 on 2024-04-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_manager', '0008_alter_inventoryitem_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarycategory',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='librarylocation',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
