# Generated by Django 5.0.3 on 2024-07-01 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_manager', '0010_alter_inventoryitem_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LibraryCategory',
            new_name='LibraryCategoryShelfmark',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='category',
            new_name='category_shelfmark',
        ),
    ]
