# Generated by Django 5.0.3 on 2024-07-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_manager', '0013_rename_name_librarycategoryshelfmark_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarycategoryshelfmark',
            options={'ordering': ['category']},
        ),
        migrations.AlterField(
            model_name='librarycategoryshelfmark',
            name='shelfmark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
