# Generated by Django 5.0.3 on 2024-07-09 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_manager', '0014_alter_librarycategoryshelfmark_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='author',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category_shelfmark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library_manager.librarycategoryshelfmark'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventory_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library_manager.librarylocation'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='librarycategoryshelfmark',
            name='category',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='librarycategoryshelfmark',
            name='shelfmark',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='librarylocation',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='library_manager.librarystatus'),
            preserve_default=False,
        ),
    ]
