# Generated by Django 5.0.3 on 2024-07-10 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_manager', '0015_librarystatus_alter_inventoryitem_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventory_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.CreateModel(
            name='LibraryBorrowedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('school_class', models.CharField(max_length=100)),
                ('borrowing_date', models.DateField()),
                ('return_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library_manager.inventoryitem')),
            ],
        ),
    ]
