# Generated by Django 5.0.3 on 2024-07-10 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_manager', '0016_alter_inventoryitem_inventory_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryBorrowedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('school_class', models.CharField(max_length=100)),
                ('borrowing_date', models.DateField(blank=True)),
                ('return_date', models.DateField(blank=True)),
                ('book', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='library_manager.inventoryitem')),
            ],
        ),
        migrations.DeleteModel(
            name='LibraryBorrowedItems',
        ),
    ]
