# Generated by Django 5.0.3 on 2024-07-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_manager', '0017_libraryborroweditem_delete_libraryborroweditems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryborroweditem',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
