# Generated by Django 5.0.3 on 2024-07-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_manager', '0018_alter_libraryborroweditem_return_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libraryborroweditem',
            options={'ordering': ['return_date']},
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventory_number',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
